language: r
cache: packages

os:
  - linux

r:
  - bioc-devel
  - bioc-release
  - 3.4.0

matrix:
  allow_failures:
    - r: bioc-devel 

bioc_required: true

r_packages:
  - covr
	
addons:
  apt:
	  packages:
		  - ghostscript

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = "R/zzz.R")'
